# ルール一覧
# https://realm.github.io/SwiftLint/rule-directory.html

excluded:
  - GitHubActionSampleAppTests

disabled_rules:
  - notification_center_detachment
  - trailing_comma

opt_in_rules:
  - array_init
  - async_without_await
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - direct_return
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - no_empty_block
  - non_overridable_class_declaration
  - number_separator
  - one_declaration_per_file
  - operator_usage_whitespace
  - optional_enum_case_matching
  - pattern_matching_keywords
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_swiftui_state
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - sorted_enum_cases
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

function_body_length:
  - 300 # warning
  - 500 # error

generic_type_name:
  min_length: 1
  max_length: 30

identifier_name:
  min_length: 2
  max_length: 30

line_length: 100

# 端的で簡潔な命名を推奨する
type_name:
  min_length: 3
  max_length: 30

# SwiftUIでの長い宣言を抑制する
closure_body_length:
  warning: 50
  error: 100

# ObjCの型を許可する場合は明示的に記載する
legacy_objc_type:
  allowed_types: []