name SwiftLint:

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint: 
    runs-on: macos_latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint