# name: SwiftLint
# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize
#     branches:
#       - main

# jobs:
#   lint: 
#     runs-on: macos_latest
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v4
#       - name: Install SwiftLint
#         run: brew install swiftlint
#       - name: Run SwiftLint
#         run: swiftlint


name: Danger Swift

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  danger:
    name: Run Danger Swift
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.1'
      - name: Danger
        uses: danger/swift@3.15.0
        with:
          arg: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}