name SwiftLint:

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint: 
    runs_on: macos_latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        uses: brew install swiftlint

      - name: Run SwiftLint
        uses: swiftlint