# name: SwiftLint
# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize
#     branches:
#       - main

# jobs:
#   lint: 
#     runs-on: macos_latest
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v4
#       - name: Install SwiftLint
#         run: brew install swiftlint
#       - name: Run SwiftLint
#         run: swiftlint


name: Danger Swift

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  danger:
    name: Run Danger Swift
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Danger SwiftLint
        uses: 417-72KI/danger-swiftlint@v6.1
        with:
          arg: --failOnErrors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-tests:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1"

      - name: Show project structure
        run: |
          echo "Current directory: $(pwd)"
          echo "List of files:"
          ls -al
          echo "Searching for .xcodeproj recursively:"
          find . -name "*.xcodeproj"

      - name: UnitTests
        run: xcodebuild test \
              -project GitHubActionSampleApp.xcodeproj \
              -scheme GitHubActionSampleApp \
              -sdk iphonesimulator \
              -destination platform='iOS Simulator,name=iPhone 16,OS=18.2'

      # - name: Danger
      #   uses: danger/swift@3.21.1
      #   with:
      #     arg: --failOnErrors --no-publish-check
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      